// trow an error
const throwAnError = () => {
    throw new Error('something went wrong');
}

module.exports = throwAnError